### ISSUE TITLE
Investigate S3, CloudFront review

### ISSUE THREAD

**Issue by iamslash** [iamslash/devinterview#2]

**Comment by hojinlee** [comment]
http://pyrasis.com/book/TheArtOfAmazonWebServices/Chapter11
https://bcho.tistory.com/778

**S3(Simple Storage Service)** 기본 개념

객체(Object): S3에 데이터가 저장되는 최소 단위입니다. 이 객체는 파일과 메타데이터로 구성
키(Key): 객체의 이름, 값(Value): 객체의 데이터 
객체 하나의 크기는 1바이트부터 5테라바이트(TB)까지
메타데이터는 HTTP Content-Type 형식(MIME) 입니다. 파일의 확장자에 따라 자동으로 설정되며 임의로 설정할 수도 있습니다. 키-값(Key-Value) 형식이며 S3 전용 메타데이터 및 사용자 정의 메타데이터도 저장
버킷(bucket): S3에서 생성할 수 있는 최상위 폴더, 리전별로 생성, 이름은 모든 S3 리전 중에서 유일해야, 계정 별로 100개까지 생성,버킷 안에 객체가 저장
폴더(디렉터리) 생성 가능이 가능(실제로는 객체 이름이 디렉터리 경로까지 포함하고 있습니다).
저장 가능한 객체의 개수는 무제한
저장 가능한 용량은 무제한
접속 제어 및 권한 관리가 가능
http://examplebucket.s3.amazonaws.com/helloworld.jpg 처럼 URL로 접근이 가능. 여기서 examplebucket은 버킷, helloworld.jpg은 객체
내구성과 가용성: 1년 기준으로 99.999999999% 내구성, 99.99% 가용성. 내구성은 데이터가 유실되지 않는 것을 뜻하며 가용성은 언제나 정상적으로 사용 가능한 상태를 의미
요금: 저장 용량과 데이터 전송량, HTTP 요청(Request) 개수로 책정

--------------------------------------------------------
https://docs.aws.amazon.com/ko_kr/AmazonCloudFront/latest/DeveloperGuide/Introduction.html

**CloudFront** 

Amazon CloudFront는 .html, .css, .js 및 이미지 파일과 같은 정적 및 동적 웹 콘텐츠를 사용자에게 더 빨리 배포하도록 지원하는 웹 서비스
엣지 로케이션이라고 하는 데이터 센터의 전 세계 네트워크를 통해 콘텐츠를 제공. CloudFront를 통해 서비스하는 콘텐츠를 사용자가 요청하면 지연 시간이 가장 낮은 엣지 로케이션으로 라우팅되므로 콘텐츠 전송 성능이 뛰어남

콘텐츠가 이미 지연 시간이 가장 낮은 엣지에 있는 경우 CloudFront가 콘텐츠를 즉시 제공.

콘텐츠가 엣지 로케이션에 없는 경우 CloudFront는 콘텐츠의 최종 버전에 대한 소스로 지정된 오리진—예: Amazon S3 버킷, MediaPackage 채널, HTTP 서버(예: 웹 서버) 등에서 콘텐츠를 검색
